# This YAML file contains the CircleCI configuration for the LuckyPicker project.
# It specifies the version of the configuration file and includes the 'node' orb.
version: 2.1
orbs:
  node: circleci/node@5.1.0
  win: circleci/windows@5.0

jobs:
  build_ubuntu:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y dpkg fakeroot lintian build-essential rpm flatpak flatpak-builder
            npm install
      - run:
          name: Build Ubuntu deb and rpm
          command: npm run make --platform=linux --arch=x64
      - run:
          name: Upload deb and rpm
          command: |
            mkdir /tmp/artifacts;
            find /home/circleci/project/out/make/deb/x64/ -name "*.deb" -exec mv {} /tmp/artifacts \;
            find /home/circleci/project/out/make/rpm/x64/ -name "*.rpm" -exec mv {} /tmp/artifacts \;
      - store_artifacts:
          path: /tmp/artifacts

  build_windows:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: Setting Github Name and Email
          command: |
            git config --global user.email "xiaoda@duck.com"
            git config --global user.name "zdxiaoda"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Windows
          command: npm run make --platform=windows
      - run:
          name: Upload Windows
          command: |
            mkdir /tmp/artifacts;
            mv @out/make/squirrel.windows/x64/*.exe" /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  build_mac:
    macos:
      xcode: 14.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Mac
          command: npm run make --platform=mac
      - run:
          name: Upload Mac
          command: |
            mkdir /tmp/artifacts;
            mv /Users/distiller/project/out/make/* /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  build:
    jobs:
      - build_ubuntu
      - build_windows
      - build_mac
