version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node


    working_directory: ~/project

    steps:
      - checkout
      
      # 安装依赖
      - run:
          name: Install Dependencies
          command: npm install

      # 构建 Electron
      - run:
          name: Build Electron
          command: npm run build-electron

      # 保存编译结果为工件
      - save_cache:
          key: project-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - out # 编译输出文件夹路径

      - store_artifacts:
          path: out # 工件存储的路径
          destination: electron-builds # 工件在 CircleCI 上的目标路径
