# This YAML file contains the CircleCI configuration for the LuckyPicker project.
# It specifies the version of the configuration file and includes the 'node' orb.
version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_ubuntu:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y dpkg fakeroot lintian build-essential rpm flatpak flatpak-builder
            npm install
      - run:
          name: Build Ubuntu
          command: npm run make --linux

  build_windows:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Windows
          command: npm run make --win

  build_mac:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Mac
          command: npm run make --mac

workflows:
  build:
    jobs:
      - build_ubuntu
      - build_windows
      - build_mac
