# This YAML file contains the CircleCI configuration for the LuckyPicker project.
# It specifies the version of the configuration file and includes the 'node' orb.
version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_ubuntu:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y dpkg fakeroot lintian build-essential rpm flatpak flatpak-builder
            npm install
      - run:
          name: Build Ubuntu deb and rpm
          command: npm run make --platform=linux --arch=x64 --target=deb --target=rpm
      - run:
          name: Build Flatpak
          command: npx electron-forge make --target=flatpak --arch=x64
          
  build_windows:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Windows
          command: npm run make --platform=windows

  build_mac:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Mac
          command: npm run make --platform=mac

workflows:
  build:
    jobs:
      - build_ubuntu
      - build_windows
      - build_mac
