name: Linux 打包
on:
  push:
    branches:
      - master # master 分支 push 时触发工作流
jobs:
  pack: # 打包任务
    runs-on: ubuntu-22.04 # 在 Ubuntu 系统中运行
    steps:
    - uses: actions/checkout@v2 # 下载仓库代码到工作流机器中
    - name: 安装依赖并且进行构建 # 安装依赖并且进行构建
      run: |
        npm install
        npm run make
    - name: 将构建产物进行上传  file # 将构建产物进行上传
      uses: actions/upload-artifact@v2
      with:
        name: 随机点名系统_快速构建_Linux_X64 # 上传后的名字
        path: out/make/* # 将 deb/rpm 文件进行上传
